version: '3.8'
services:
  app:
    build: .
    depends_on:
      - redis
    env_file: .env
    ports:
      - "8080:8080"
    volumes:
      - ./:/app

  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
    volumes:
      - ./redis:/data
